# This .yaml cofinguration file contains all variables used by the snakemake pipeline
# DO NOT CHANGE parameter names without changing it in Snakefile as well
# On the other hand, some parameter values have to be inevitably modifed
# **********************************************************************************************************************************

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  SPACCa ChIP-seq analyses  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

### 0. General workflow parameters
workflow_configuration:
  runs_directory: "/path/to/your/bams"
  output_directory: "/path/to/output/folder"
  sample_config_table: "/path/to/the/sample_config.txt"

bam_features:
  bam_suffix: "_mapq20_mdup_sorted.bam"
  umi_present: False
  paired_end: False
  skip_bam_filtering: True
  remove_duplicates: False
  MAPQ_threshold: 20

genomic_annotations:
  genome_id: "hg19"
  genome_fasta: "/path/to/hg19_genome.fa"
  blacklist: "/path/to/hg19-blacklist.v2.bed"
  effective_genomeSize: 2900338458
  ignore_for_normalization: "X Y MT M GL000207.1 GL000226.1 GL000229.1 GL000231.1 GL000210.1 GL000239.1 GL000235.1 GL000201.1 GL000247.1 GL000245.1 GL000197.1 GL000203.1 GL000246.1 GL000249.1 GL000196.1 GL000248.1 GL000244.1 GL000238.1 GL000202.1 GL000234.1 GL000232.1 GL000206.1 GL000240.1 GL000236.1 GL000241.1 GL000243.1 GL000242.1 GL000230.1 GL000237.1 GL000233.1 GL000204.1 GL000198.1 GL000208.1 GL000191.1 GL000227.1 GL000228.1 GL000214.1 GL000221.1 GL000209.1 GL000218.1 GL000220.1 GL000213.1 GL000211.1 GL000199.1 GL000217.1 GL000216.1 GL000215.1 GL000205.1 GL000219.1 GL000224.1 GL000223.1 GL000195.1 GL000212.1 GL000222.1 GL000200.1 GL000193.1 GL000194.1 GL000225.1 GL000192.1 NC_007605 hs37d5"



### 1. BigWig generation and normalizatioon
bigWig_binSize: 10

### 2. Peak calling
use_macs3: False
macs_qValue_cutoff: 0.01

### 3. Quality check
perform_plotFingerprint: False
perform_fragmentSizeDistribution: False
fragment_length: 200
correlation_heatmap_colorMap: 'PuBuGn'


### 4. GC-bias correction
GCbias_correction:
  correct_GCbias: False
  GCbias_fragment_length: 200


### 5. Somatic Variants
somatic_variants:
  call_variants: True
  dbsnp_file: "/path/to/dbsnp_file.vcf.gz"
  DP_snp_threshold: 20
  QUAL_snp_threshold: 0
  DP_indel_threshold: 20
  QUAL_indel_threshold: 0
  SnpSift_vcf_fields_to_extract: [ "CHROM", "POS", "ID", "REF", "ALT", "QUAL", "DP", "AF", "FILTER", "FORMAT", "GEN[*].GT", "GEN[*].AD", "GEN[*].AF" ]


### 6. Copy Number Variations
copy_number_variation:
  call_CNV: True
  kb_bin_resolution: 20
  CNA_threshold: 2
  CNA_plot_line_colors: "red"
  CNA_plot_point_size: 0.5
  CNA_plot_point_transparency: 0.5
